language: node_js
node_js:
  - 14

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests. Yes there will be tests"

script:
  ## Build
  - docker --version
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  ## Tagging
  - docker tag udagram-reverseproxy ttnguyen115/udagram-reverseproxy:v2
  - docker tag udagram-api-feed ttnguyen115/udagram-api-feed:v2
  - docker tag udagram-api-user ttnguyen115/udagram-api-user:v2
  - docker tag udagram-frontend ttnguyen115/udagram-frontend:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ttnguyen115/udagram-reverseproxy:v2
  - docker push ttnguyen115/udagram-api-feed:v2
  - docker push ttnguyen115/udagram-api-user:v2
  - docker push ttnguyen115/udagram-frontend:v3
